### PR TITLE
Add support for the latest ECMAScript standard (ES2016)

### PR DESCRIPTION
**Pull request by lydell**

### CODE REVIEW

**Comment by paulmillr** [comment]
The Travis is failing.

**Comment by lydell** [comment]
Travis passes on Node.js 5 and fails on Node.js 4. Unfortunately the assertion errors aren't caught, so I have no clue what happens. (Instead, the assertions simply prevent the `done` callback from being called, causing timeout errors.)

Considering that [brunch itself only tests on Node.js 5 and 6](https://github.com/brunch/brunch/blob/ef639d4c622a028d33b7f2d4a6b26c391d503d92/.travis.yml#L6-L8), I suggest that we simply drop Node.js 4 support and call it a day.

**Comment by paulmillr** [comment]
no. brunch still supports node 4

**Comment by lydell** [comment]
Odd. I can’t reproduce the test failures locally.

```
$ node --version
v4.4.7   # Same as on Travis.
$ npm test

> babel-brunch@6.0.4 test /home/lydell/forks/babel-brunch
> eslint index.js && mocha



  Plugin
    ✓ should be an object
    ✓ should have #compile method
    ✓ should do nothing for no preset
    ✓ should compile and produce valid result (105ms)
    ✓ should load indicated plugins
    ✓ should produce source maps
    ✓ should pass through content of ignored paths
    custom file extensions & patterns
      ✓ should handle custom file extensions
      ✓ should properly link to source file in source maps


  9 passing (198ms)
```

**Pull request merged**
