### PR TITLE
update babel to v7

### PR DESCRIPTION
**Pull request by soumak77**
resolves https://github.com/babel/babel-brunch/issues/63

### CODE REVIEW

**Comment by soumak77** [comment]
@paulmillr any chance you can take a look at this PR?

**Comment by soumak77** [comment]
@shvaikalesh can you take a look at this?

**Comment by yavorsky** [comment]
@soumak77 LGTM, but unfortunately, I haven't access rights to merge for `babel-brunch` project.

**Comment by soumak77** [comment]
@paulmillr is this repo still being maintained?

**Comment by shvaikalesh** [comment]
We will definitely get this in after `@babel/core` v7 will be released.

**Comment by AlexandreBourdeaudhui** [comment]
`@babel/core` v7 is released since 2 days. Please merge and publish a new release 🙏.

**Comment by paulmillr** [comment]
it's out folks

**Pull request closed without merging**
